spring:
  # Database config
  datasource:
    url: ${dev.database.url}
    username: ${dev.database.username}
    password: ${dev.database.password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}
    prefer-ip-address: true

microservices:
  coupon-service:
    endpoints:
      endpoint:
        uri: http://coupon-service:9091/api/v1/coupons
